// frontend/digitalfix-react/src/App.jsx
import { Link, Navigate, Route, Routes } from 'react-router-dom';
import { useIsAuthenticated } from '@azure/msal-react';
import ProtectedRoute from './components/ProtectedRoute';
import WorkOrdersPage from './pages/WorkOrdersPage';
import ForbiddenPage from './pages/ForbiddenPage';
import { login, logout } from './services/authService';

export default function App() {
  const isAuthenticated = useIsAuthenticated();

  return (
    <div>
      <nav>
        <Link to="/workorders">Órdenes de trabajo</Link>
        {isAuthenticated ? (
          <button onClick={logout}>Cerrar sesión</button>
        ) : (
          <button onClick={login}>Iniciar sesión</button>
        )}
      </nav>

      <Routes>
        <Route path="/" element={<Navigate to="/workorders" replace />} />
        <Route element={<ProtectedRoute roles={['Admin', 'Supervisor', 'Cliente']} />}>
          <Route path="/workorders" element={<WorkOrdersPage />} />
        </Route>
        <Route path="/forbidden" element={<ForbiddenPage />} />
        <Route path="*" element={<Navigate to="/workorders" replace />} />
      </Routes>
    </div>
  );
}

// frontend/digitalfix-web/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';
import { NgIf } from '@angular/common';
import { AuthService } from './core/auth/auth.service';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, NgIf],
  template: `
    <nav>
      <a routerLink="/workorders">Órdenes de trabajo</a>
      <span *ngIf="auth.isAuthenticated()">Bienvenido, {{ auth.getActiveAccount()?.name }}</span>
      <button *ngIf="!auth.isAuthenticated()" (click)="auth.login()">Iniciar sesión</button>
      <button *ngIf="auth.isAuthenticated()" (click)="auth.logout()">Cerrar sesión</button>
    </nav>
    <router-outlet></router-outlet>
  `
})
export class AppComponent {
  constructor(public readonly auth: AuthService) {}
}
